FROM nginx:1.27-alpine

WORKDIR /var/www/html

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

RUN addgroup -g 1000 app \
  && adduser -G app -g app -s /bin/sh -D app -u 1000 \
  && sed -i 's/^user  nginx;/user app;/' /etc/nginx/nginx.conf

# Only what nginx needs
COPY public ./public

RUN rm -rf public/storage \
  && ln -s ../storage/app/public public/storage

EXPOSE 80
